### PR TITLE
Serialization traits for Transaction struct

### PR DESCRIPTION
**Pull request by nadtech-hub**
## Motivation

It brings implementation of Serialize, Deserialize traits for Transaction struct. It should close [1409](https://github.com/alloy-rs/alloy/issues/1409)

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
hmm, wouldn't this become a non issue with #1460 @klkvr ?

**Comment by nadtech-hub** [comment]
I read EIPs of all tx types while implementing serialization. I guess it may need refactoring after merging envelope implementation you refered.

**Comment by klkvr** [comment]
> hmm, wouldn't this become a non issue with #1460 @klkvr ?

yep, I think it would

**Comment by nadtech-hub** [comment]
I incline to agree with your point

**Comment by nadtech-hub** [comment]
So I close this one?

**Comment by mattsse** [comment]
yeah, sorry about this

**Pull request closed without merging**
