### PR TITLE
chore: add codes into execution witness

### PR DESCRIPTION
**Pull request by 0x00101010**
## Motivation

Return codes in ExecutionWitness

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I don't have enough context here @Rjected @rkrasiuk

**Review by clabby — APPROVED** [review]
LGTM

**Review by Rjected — APPROVED** [review]
lgtm

**Review by mattsse — APPROVED** [review]

**Comment by 0x00101010** [comment]
@mattsse curious about the release cadence here? When do we do another revm release and upgrade in reth accordingly?

**Pull request merged**
