### PR TITLE
consensus: rm `Receipts` `root_slow` unused method

### PR DESCRIPTION
**Pull request by tcoratger**
Follow up on https://github.com/alloy-rs/alloy/pull/1563:
- Full coverage with unit tests
- Small refactor

### CODE REVIEW

**Comment by DaniPopes** [comment]
I don't see the point of this function, after changing `&[&T]` to `&[T]` because that collect is unnecessary, it becomes essentially `receipts.map(f)`, which doesn't need to be a function

**Comment by tcoratger** [comment]
> I don't see the point of this function, after changing `&[&T]` to `&[T]` because that collect is unnecessary, it becomes essentially `receipts.map(f)`, which doesn't need to be a method

@DaniPopes Yes fair point. I think it requires changing some function definitions in reth but I think it can only be beneficial. Here is what I propose:
- I have a PR open in draft on reth to work on it (and more generally the replacement of `Receipts`) https://github.com/paradigmxyz/reth/pull/12059/
- Let's do a review on it without using the `root_slow` function as you propose here.
- If it is valid then we transform this PR on alloy into a PR for the definitive removal of this function.

What do you think?

**Comment by emhane** [comment]
agree with @DaniPopes , this only makes sense if this type is the l1 type, and it implements a new trait `ReceiptsRoot`, which should then also be implemented on a similar `op-alloy` type `OpReceipts`

**Comment by tcoratger** [comment]
@emhane https://github.com/paradigmxyz/reth/pull/12059 is ready for review, if everything is fine and merged then we can delete the function here in alloy :)

**Comment by tcoratger** [comment]
@DaniPopes @emhane Given the path taken by https://github.com/paradigmxyz/reth/pull/12162, just removed this unused method

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]

**Pull request merged**
