### PR TITLE
Callbuilder implement partial eip 1559

### LINKED ISSUE #487: [Feature] Allow CallBuilder to edit max priority fee per gas
### Component

contract

### Describe the feature you would like

In the example: [deploy_from_contract](https://github.com/alloy-rs/examples/blob/main/examples/contracts/examples/deploy_from_contract.rs)

Currently to send a transaction to the smart contract, this way is used:
```rust
    let builder = contract.setNumber(U256::from(42)).nonce(1).gas(estimate).gas_price(base_fee);
    let receipt = builder.send().await?.get_receipt().await?;
```

Only the legacy `gas_price` is currently supported.

It would be nice to be able to edit other fields of the [CallBuilder](https://github.com/alloy-rs/alloy/blob/02907ed9ac0e53ff446f3931a21fefd053d3e34d/crates/contract/src/call.rs#L259) to better use the EIP1559 standard.

Like for example:
- `max_fee_per_gas`
- `max_priority_fee_per_gas`
- `access_list`

### PR DESCRIPTION
**Pull request by NicolasWent**
## Motivation

Implements #487

## Solution

Implemented a way to modify the fields:
- `max_fee_per_gas`
- `max_priority_fee_per_gas`
- `access_list`

## PR Checklist

- [x] Added Tests
    - Testing if modifications are correctly taken in account by the inner transaction object
    - Tested sending a transaction with specific `max_priority_fee_per_gas` and `max_fee_per_gas`
- [x] Added Documentation
- [ ] Breaking changes => changes shouldn't break anything

### CODE REVIEW

**Comment by gakonst** [comment]
@NicolasWent smol conflict here, any other changes you need or good to review?

**Comment by NicolasWent** [comment]
I solved the conflicts but I ended up making a rebase that broke this PR :(

**Comment by prestwich** [comment]
>  I don't know what is the next step is, should I make a new PR with only my changes?

this is fine, really whatever you think would be easiest to get a clean branch

**Comment by NicolasWent** [comment]
New version in: #625

**Pull request closed without merging**
