### PR TITLE
feat: Default to Ethereum network in `alloy-provider` and `alloy-contract`

### PR DESCRIPTION
**Pull request by moricho**
## Motivation
This PR defaults `Network` parameters to Ethereum in `alloy-provider` and `alloy-contract`.

From: https://github.com/alloy-rs/alloy/issues/263

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Comment by moricho** [comment]
Hi @onbjerg. 
In setting the default value to Network, I've rearranged the type parameters so that the Network parameter is the last. I've also made corresponding changes elsewhere. However, it appears that the `sol!` macro doesn't recognize this and triggers the following error. Should I modify the sol macro implementation in `alloy/core` as well?

```rs
error[E0277]: the trait bound `T: Network` is not satisfied
   --> crates/contract/src/call.rs:493:9
    |
493 | /         sol! {
494 | |             #[sol(rpc, bytecode = "6942")]
495 | |             contract EmptyConstructor {
496 | |                 constructor();
497 | |             }
498 | |         }
    | |_________^ the trait `Network` is not implemented for `T`
    |
note: required by a bound in `Provider`
   --> /Users/ikedamorito/src/moricho/alloy/crates/provider/src/provider.rs:178:60
    |
178 | pub trait Provider<T: Transport + Clone = BoxTransport, N: Network = Ethereum>:
    |                                                            ^^^^^^^ required by this bound in `Provider`
    = note: this error originates in the macro `sol` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `T`
    |
498 |         } alloy_network::Network
    |           ++++++++++++++++++++++
```

**Comment by onbjerg** [comment]
@moricho sorry for the delayed response, yes, you would need to adjust the type param order in `sol!` as well

**Comment by DaniPopes** [comment]
Looks fine, please fix the remaining doctest failures

**Comment by moricho** [comment]
Fixed the doctest failures ✅

**Comment by moricho** [comment]
Once https://github.com/alloy-rs/core/pull/587 is merged, I'll update the dependencies to use the latest `alloy-rs/core`

**Review by mattsse — APPROVED** [review]
switching the order here makes a lot more sense so you no longer need to specific Ethereum if you're only interested in that

pending @prestwich

**Review by mattsse — APPROVED** [review]
sorry about the conflicts -.-

@DaniPopes @prestwich we have to decide in which order we want to do this.
Merge the alloy-core companion, then release?
then update+merge this pr?

**Comment by DaniPopes** [comment]
core PR has to be merged first, then update here, and then merge this

**Review by DaniPopes — APPROVED** [review]

**Comment by prestwich** [comment]
merging, as i believe the reqs @DaniPopes set have been met

**Pull request merged**
