### PR TITLE
feat: add Http::new for reqwest::Client

### PR DESCRIPTION
**Pull request by nkysg**
## Motivation
close https://github.com/alloy-rs/alloy/issues/387

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm

**Review by prestwich — CHANGES_REQUESTED** [review]
this prevents us from using `new` to instantiate Http<hyper::Whatever>`. I would rather match the pattern eslewhere in the repo `new_hyper` and `new_reqwest`

could we instead take this as a chance to address #397 ?

**Comment by nkysg** [comment]
> this prevents us from using `new` to instantiate Httphyper::Whatever`. I would rather match the pattern eslewhere in the repo `new_hyper`and`new_reqwest`
> 
> could we instead take this as a chance to address #397 ?

do you want to implement impl Http<HyperClient>::new ?

**Review by prestwich — APPROVED** [review]
> this prevents us from using new to instantiate Http<hyper::Whatever>. I would rather match the pattern eslewhere in the repo new_hyper and new_reqwest

after #462 the naming convention is `new` and `new_hyper` so I'm approving this PR

**Pull request merged**
