### PR TITLE
refactor: make optional BlockId params required in provider functions

### PR DESCRIPTION
**Pull request by EmperorOrokuSaki**
## Motivation

This issue #514 

## Solution

Make the `BlockId` optional and use the default value if it's `None`.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [x] Breaking changes

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
the tag is a required argument,

I think the option does not improve the API, because None is equal to `Default::default()` or `BlockId::latest()`

**Comment by EmperorOrokuSaki** [comment]
> the tag is a required argument,
> 
> I think the option does not improve the API, because None is equal to `Default::default()` or `BlockId::latest()`

That is true, it is a required parameter in the RPC specification, but the other examples provided in the original issue have the same condition so it's a case of inconsistency a bit. I checked those methods and for those it's also required in the specification.

**Comment by mattsse** [comment]
I see, then we should change all `Option<BlockId>` to `BlockId`

**Comment by EmperorOrokuSaki** [comment]
> I see, then we should change all `Option<BlockId>` to `BlockId`
Sounds good. I'll change them in this pr.

**Comment by EmperorOrokuSaki** [comment]
In some files previously `None` was supplied when the arg was of the type `Option<BlockId>`, I changed those to `BlockId::default()` since that was the final value.

**Comment by prestwich** [comment]
> I think the option does not improve the API, because None is equal to Default::default() or BlockId::latest()

The only improvement is writing `None` is fewer characters than `Default::default()`. Seems kinda pointless. in favor of this change

**Comment by prestwich** [comment]
alternate API designs would be to bifurcate, which seems ok-but-verbose on our end

```
fn call_with_block(..., block_id: BlockId)
fn call(...) { self.call_with_block(..., Default::default()) }
``` 

or to switch to a rpc builder pattern for return values of those types. which seems bad

**Review by prestwich — APPROVED** [review]

**Pull request merged**
