### PR TITLE
feat(alloy-rpc-types-eth): Optional serde

### PR DESCRIPTION
**Pull request by refcell**
### Description

Downstream crates would like to use types from `alloy-rpc-types-eth` without the need for `serde` support. This PR places serialization for core eth types behind the `serde` feature flag that is enabled-by-default.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this seems fine, since all tests basically use serde we could derive serde for tests as well, but this would now require changing all attributes, so I'm fine with this.

would appreciate one additional sanity review @klkvr @DaniPopes

**Review by klkvr — APPROVED** [review]
lgtm! wondering if need for this means we are missing something in consensus types?

had a feeling that rpc-types were supposed to always implement serde as they should only be used to communicate with RPC, so curious to learn more about usecases needing this change

**Comment by mattsse** [comment]
actually, @refcell is this a size related issue?

because this will still pull in serde via alloy-serde I believe

**Comment by refcell** [comment]
> actually, @refcell is this a size related issue?
> 
> because this will still pull in serde via alloy-serde I believe

Good point, it was to decrease size and generally make available lighter types. Wonder if I can place alloy-serde behind the feature flag as well

**Comment by mattsse** [comment]
should be possible to make it optional

**Comment by mattsse** [comment]
actually, let me take a look at the engine type crate

**Comment by mattsse** [comment]
ref https://github.com/alloy-rs/alloy/pull/1280

**Pull request merged**
