### PR TITLE
refactor: rm `into_request`

### PR DESCRIPTION
**Pull request by tcoratger**
The `into_request` function that transforms a rpc `Transaction` to a rpc `TransactionRequest` was redundant and less Rust idiomatic than the `From<Transaction> for TransactionRequest` implementation. 

As a result, the `into_request` function is removed and its content is migrated to `From<Transaction> for TransactionRequest` implementation.

### CODE REVIEW

**Review by prestwich — APPROVED** [review]

**Comment by prestwich** [comment]
rebase after #724

**Review by Evalir — APPROVED** [review]

**Review by DaniPopes — COMMENTED** [review]
I don't really like this type of changes, since it requires importing the other type to convert to it either with .into or ::from.

**Comment by prestwich** [comment]
i'm fine closing it if we don't like it

**Comment by mattsse** [comment]
agree with @DaniPopes 

I prefer separate into calls,

**Pull request closed without merging**
