### PR TITLE
Implement `is_zero` method for `U64HexOrNumber`

### PR DESCRIPTION
**Pull request by tcoratger**
## Solution

Implement `is_zero` method for `U64HexOrNumber`.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I think this could be useful when used in manual serde impls

**Comment by prestwich** [comment]
i believe this is redundant code, as ruint uints support deserializing from number without any typewrapping or decoration 

serde helpers were not examined when porting from ethers so there have been a few redundant things 😅

**Comment by prestwich** [comment]
ref https://github.com/recmo/uint/blob/main/src/support/serde.rs#L127

**Comment by prestwich** [comment]
on consideration, we might want to rename the helpers something like `u64_via_ruint` to clarify behavior

**Pull request merged**
