### PR TITLE
avoid unnecessary serialize for RequestPacket.

### PR DESCRIPTION
**Pull request by robinsdan**
## Motivation

Current implementation will serialize the request twice: `Reqeust<Params>` -> `SerializedRequest` -> `hyper/reqwest request's json body`.

## Solution

Replace `RequestPacket::serialize(&self)` with  `RequestPacket::serialize(self)`, we can avoid the second serialize for hyper client.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Review by prestwich — APPROVED** [review]

**Comment by prestwich** [comment]
CI failure is unrelated, @Evalir is fixing :)

**Comment by prestwich** [comment]
can you rebase on latest main for me?

**Comment by Evalir** [comment]
@prestwich done!

**Review by Evalir — APPROVED** [review]
ty!

**Pull request merged**
