### PR TITLE
 refactor: rename "blob_gas_price" to "blob_base_fee"

### PR DESCRIPTION
**Pull request by AbnerZheng**
## Motivation
According to https://github.com/paradigmxyz/reth/issues/6330, `blob_gas_price` should renamed to `blob_base_fee`. 

## Solution
A minor update.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Comment by AbnerZheng** [comment]
@mattsse PTAL

**Review by mattsse — COMMENTED** [review]
thanks, I need think about this a bit because

https://github.com/ethereum/go-ethereum/blob/b590cae89232299d54aac8aada88c66d00c5b34c/internal/ethapi/api.go#L1722-L1722

**Comment by prestwich** [comment]
@mattsse is this still being considered?

**Comment by mattsse** [comment]
the spec is blobGasPrice, which is in line with other `*Price` fields of the receipt, so we can close this

**Pull request closed without merging**
