### PR TITLE
fix(prelude): enable `rpc-client` exports, enable `pubsub` on `provider` and add missing exports from `alloy/core`

### LINKED ISSUE #391: [Feature] Improve and complete `alloy` prelude crate feature flag compatiblity
### Component

provider, pubsub, rpc

### Describe the feature you would like

In order to allow users to use the `alloy` namespace to access all features we need to make sure there is full feature flag coverage of crates and we maintain that coverage. Another goal is to reduce the amount of individual feature flags by having a few high level feature flags which enable general code paths alongside individual specific feature flags.

Concretely we are currently missing the following feature flag exports:

- `alloy-rpc-client`:
  - `reqwest`
  - `hyper`
  - `pubsub`
  - `ws`
  - `ipc`
  
- `alloy-provider`
  - `provider-ws` misses `alloy-provider?/pubsub` flag
  - `provider-ipc` misses `alloy-provider?/pubsub` flag

- `alloy/core`
  - `native-keccak`

Other issues to resolve:

- Default to `std` as a default feature but support `no_std`
- Export missing `serde` feature flag
- Export all crates from `alloy/core`
- Refactor, clean up and regroup of feature flags

### Additional context

Related PR: #421

### PR DESCRIPTION
**Pull request by zerosnacks**
## Motivation

Related to #391, has a mirror PR for `alloy/examples` here: https://github.com/alloy-rs/examples/pull/37

## Solution

- Enables the `pubsub` feature on `alloy-provider` when using `provider-ws` or `provider-ipc`
- Exports `rpc-client-http-reqwest`, `rpc-client-http-hyper`, `rpc-client-ws`, `rpc-client-ipc` as feature flags. It possibly makes sense to add a `rpc-client-pubsub` feature flag but I did not see an immediate reason.

Additive:
- Added missing `native-keccak` flag that was not re-exported from `alloy/core`.

This PR is intended to be non-breaking.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Comment by zerosnacks** [comment]
I noticed the [alloy/serde](https://github.com/alloy-rs/alloy/tree/main/crates/serde) crate is currently not exported. Is this something we would want @prestwich? It could be useful for the `create_instances` example in `alloy/examples` as it currently does not implement a case showing the use of ethers-rs equivalent of `serde_helpers::Numeric`.

https://github.com/alloy-rs/examples/blob/main/examples/big-numbers/examples/create_instances.rs

vs

https://github.com/gakonst/ethers-rs/blob/master/examples/big-numbers/examples/create_instances.rs

**Comment by prestwich** [comment]
It should be included for the benefit of people implementing their own network types

**Comment by zerosnacks** [comment]
> It should be included for the benefit of people implementing their own network types

Makes sense, I've decided to split up https://github.com/alloy-rs/alloy/issues/391 into two parts, one with non-breaking changes with relatively high priority (this PR) and a follow up more major PR that would include a larger refactor, additional exports (like `serde`) with proposed breaking changes and will likely requires some further discussion (see https://github.com/alloy-rs/alloy/issues/391).

I'm moving this out of draft again so it can be reviewed and downstream tickets can become unblocked.

**Comment by zerosnacks** [comment]
Closing this in favor of larger ticket that handles the refactor as more issues have popped up and the impact of (if any) breaking changes appears to be small.

**Pull request closed without merging**
